artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/zzAzuka/Data-Storage/raw/refs/heads/main/TCC_Train_Data_New.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  features: 200000
  output_len: 1800

model_train:
  root_dir: artifacts/model_train
  trained_model_path: artifacts/model_train/trained_model.h5
  features: 200000
  loss: BinaryCrossentropy
  optimizer: Adam
  epochs: 1